#!/bin/bash
#
# Copyright (C) 2010-2013 by Cloud Computing Center for Mobile Applications
# Industrial Technology Research Institute
#
# It is NOT YET officially approved by OCP.
#
# check_usb_port
#   1. Retrieve dmesg log to gather USB information.
#   2. Criteria: USB version must be 2.0 or higher.
#
# Authors
#   Nelson Chu <Nelson.Chu@itri.org.tw>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

support_usb_3=`cat /var/log/dmesg |grep -i "xhci_hcd" -c`

if [ "$support_usb_3" -gt "0" ]; then
    echo "Support USB 3.0 ports."
    exit 0
fi

output=`cat /var/log/dmesg |grep -i ehci_hcd:| awk '{print $5}'`

if [ "$output" = "2.0" ]; then
    echo "Support USB 2.0 ports."
    exit 0
fi

echo "Do not support USB 2.0 ports or higher."
exit 1
