#!/bin/bash
#
# Copyright (C) 2010-2013 by Cloud Computing Center for Mobile Applications
# Industrial Technology Research Institute
#
# It is NOT YET officially approved by OCP.
#
# check_sata_port
#   1. Use dmesg command to gather SATA information.
#   2. Criteria: SATA port speed up to 6.0Gps.
#
# Authors
#   Nelson Chu <Nelson.Chu@itri.org.tw>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

output=`dmesg |grep -i "SATA link up"| awk '{print $7}'`

if [ "$output" == "6.0" ]; then
    echo "Support SATA 6Gps ports"
    exit 0
fi

echo "Do not support SATA 6Gps ports"
exit 1
