#!/usr/bin/env python3
"""
Copyright (C) 2010-2013 by Cloud Computing Center for Mobile Applications
Industrial Technology Research Institute

It is NOT YET officially approved by OCP.

raid_hdd_info
  1. Use megasasctl command to get all JBOD HDD information.
  2. Show total HDD number in JBOD and check disks readiness.
  3. Criteria: ensure all JBOD disks information and status are correct.

Authors
  Nelson Chu <Nelson.Chu@itri.org.tw>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3,
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""

import sys
from subprocess import Popen, PIPE

def main():
    command = 'megasasctl |grep -E "a[0-9]+e[0-9]+s[0-9]+ +[0-9]+GiB"'
    hdd_info = Popen(command, stdout=PIPE, stderr=PIPE,
                     shell=True).communicate()[0]
    hdd_info = hdd_info.decode('utf-8')
    disk_number = 0
    fail = 0

    # Check is there has any disk.
    if not hdd_info:
        print('There is no disk in knox.')
        return 10

    for disk in hdd_info.strip().split('\n'):
        disk_number = disk_number+1
        # Check disk status is readiness.
        if disk.strip().split(' ')[-1] != 'ready':
            fail = fail+1

    print(('Total number of %d HDDs in JBOD.') %disk_number)

    if fail:
        print(('There are %d disks status not in ready.') %fail)
        return 20

    return 0

if __name__ == '__main__':
    sys.exit(main())
